title: Santiago Dubov
description: >
  **Santiago Dubov**, Masters student in machine learning at the University of Cambridge with a passion for data science.
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: 
linkedin_username: "#"
github_username:  "#"
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
