title: Santiago Dubov
description: >
  **I am Santiago Dubov**, Masters student in machine learning with a passion for data science.
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
linkedin_username: "#"
github_username:  "#"
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
